import { ArrowLeft, Building2, CheckCircle2, Edit3, ExternalLink, Image as ImageIcon, MapPin, Power } from 'lucide-react'
import { useState } from 'react'
import { Link, useLocation, useParams } from 'react-router'
import DestinationMap from '../../components/DestinationMap/DestinationMap.jsx'
import DestinationStatusModal from '../../components/DestinationStatusModal/DestinationStatusModal.jsx'
import useDestinations from '../../context/useDestinations.js'
import useHotels from '../../context/useHotels.js'
import { AttractionIcon, ThemeIcon } from '../../utils/destinationIcons.jsx'
import { DESTINATION_STATUS, calculateDistanceKm, formatDistanceKm, getActiveAttractions, getAttractionType, getDestinationThemes, getHotelsForDestination } from '../../utils/destinationDomain.js'
import './DestinationDetailsManagement.css'

export default function DestinationDetailsManagement() {
  const { id } = useParams(); const route = useLocation()
  const { getDestinationById, approveDestination, reactivateDestination, deactivateDestination } = useDestinations()
  const { hotels } = useHotels(); const destination = getDestinationById(id)
  const [deactivate, setDeactivate] = useState(false)
  const [notice, setNotice] = useState(route.state?.created ? 'Destination created successfully.' : route.state?.updated ? 'Destination updated successfully.' : '')
  const [imageFailed, setImageFailed] = useState(false)
  if (!destination) return <section className="destination-management-not-found"><MapPin size={30} /><h1>Destination Not Found</h1><p>The requested shared Destination record does not exist.</p><Link to="/management/destinations"><ArrowLeft size={16} />Back to Destinations</Link></section>
  const linked = getHotelsForDestination(hotels, destination.id); const themes = getDestinationThemes(destination); const attractions = [...(destination.attractions || [])].sort((a, b) => a.displayOrder - b.displayOrder)
  const focalPosition = `${destination.imageFocalPoint?.x ?? 50}% ${destination.imageFocalPoint?.y ?? 50}%`
  const editRoute = `/management/destinations/${destination.id}/edit`
  return <section className="destination-management-details"><Link className="destination-details-back" to="/management/destinations"><ArrowLeft size={17} />Back to Destinations</Link>
    <header><div><span>Destination record</span><h1>{destination.name}</h1><div><strong className={`destination-status-badge destination-status-badge--${destination.status.toLowerCase()}`}>{destination.status.replaceAll('_', ' ')}</strong><small>{linked.length} {linked.length === 1 ? 'Hotel' : 'Hotels'} · {destination.region}</small></div></div><nav><Link to={editRoute}><Edit3 size={16} />{destination.status === DESTINATION_STATUS.DRAFT ? 'Continue Setup' : 'Edit Destination'}</Link>{destination.status === DESTINATION_STATUS.ACTIVE && <Link to={`/destinations/${destination.slug}`}><ExternalLink size={16} />View Customer Page</Link>}{destination.status === DESTINATION_STATUS.READY_FOR_REVIEW && <button type="button" onClick={() => { approveDestination(destination.id); setNotice('Destination approved and published successfully.') }}><CheckCircle2 size={16} />Approve & Publish</button>}{destination.status === DESTINATION_STATUS.ACTIVE && <button type="button" onClick={() => setDeactivate(true)}><Power size={16} />Deactivate</button>}{destination.status === DESTINATION_STATUS.INACTIVE && <button type="button" onClick={() => { reactivateDestination(destination.id); setNotice('Destination reactivated successfully.') }}><Power size={16} />Reactivate</button>}</nav></header>{notice && <p className="destination-details-notice" role="status">{notice}</p>}
    <article className="destination-details-hero">{!imageFailed && destination.mainImage ? <img src={destination.mainImage} alt={`${destination.name}, Sri Lanka`} style={{ objectPosition: focalPosition }} onError={() => setImageFailed(true)} /> : <div className="destination-details-image-fallback"><ImageIcon size={34} /><span>Main image unavailable</span></div>}<div><span>{destination.region}{destination.district ? ` · ${destination.district} District` : ''}</span><h2>{destination.shortDescription}</h2><div>{themes.map((theme) => <small key={theme.key}><ThemeIcon themeKey={theme.key} size={14} />{theme.label}</small>)}</div></div></article>
    <div className="destination-details-grid"><article><span className="details-eyebrow">Destination information</span><h2>About {destination.name}</h2>{destination.fullDescription.split(/\n+/).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<dl><div><dt>Province</dt><dd>{destination.region}</dd></div><div><dt>District</dt><dd>{destination.district || 'Not configured'}</dd></div><div><dt>Slug</dt><dd>{destination.slug}</dd></div><div><dt>Last Updated</dt><dd>{destination.lastUpdatedAt || destination.updatedAt ? new Date(destination.lastUpdatedAt || destination.updatedAt).toLocaleString('en-GB') : 'Initial frontend data'}<small>{destination.lastUpdatedSection || 'Destination record'}</small></dd></div></dl></article><article><span className="details-eyebrow">Customer content</span><h2>Highlights</h2>{destination.highlights.length ? <ul className="destination-detail-tags">{destination.highlights.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="destination-detail-empty">No Highlights added yet.</p>}<h2>Travel Themes</h2><ul className="destination-detail-tags themes">{themes.map((theme) => <li key={theme.key}><ThemeIcon themeKey={theme.key} size={14} />{theme.label}</li>)}</ul></article></div>
    <article className="destination-details-section"><div className="destination-linked-heading"><div><span>Curated places</span><h2>Nearby Attractions</h2><p>{getActiveAttractions(destination).length} active · {attractions.length - getActiveAttractions(destination).length} inactive</p></div><Link to={`${editRoute}?step=5&section=attractions`}>Manage Attractions</Link></div>{attractions.length ? <div className="destination-attraction-cards">{attractions.map((item) => <article key={item.id}><div className="destination-attraction-media">{item.image ? <img src={item.image} alt="" /> : <AttractionIcon type={item.type} size={23} />}</div><div><strong>{item.name}</strong><small>{getAttractionType(item.type).label} · {formatDistanceKm(calculateDistanceKm(destination, item)) || 'Location pending'} from Destination centre</small><p>{item.shortDescription || 'No description added.'}</p></div><span className={`attraction-status attraction-status--${item.status.toLowerCase()}`}>{item.status}</span></article>)}</div> : <p className="destination-detail-empty">No Nearby Attractions added yet.</p>}</article>
    <article className="destination-details-section destination-map-section"><div className="destination-linked-heading"><div><span>Location context</span><h2>Destination & Attraction Map</h2><p>{destination.region}{destination.district ? ` · ${destination.district} District` : ''}</p></div></div><div className="destination-map-shell"><DestinationMap destination={destination} /></div></article>
    <article className="destination-details-section"><div className="destination-linked-heading"><div><span>Shared Hotel relationships</span><h2>Hotels in this Destination</h2></div><strong><Building2 size={16} />{linked.length} {linked.length === 1 ? 'Hotel' : 'Hotels'}</strong></div>{linked.length ? <div className="destination-linked-hotels">{linked.map((hotel) => <article key={hotel.id}><img src={hotel.mainImage || hotel.image} alt="" /><div><strong>{hotel.name}</strong><small>{hotel.publicationStatus} · {hotel.setupStatus}</small></div><Link to={`/management/hotels/${hotel.id}/setup`}>Manage Hotel</Link></article>)}</div> : <p className="destination-detail-empty">No Hotels currently use this Destination.</p>}</article>
    <DestinationStatusModal destination={deactivate ? destination : null} hotelCount={linked.length} onCancel={() => setDeactivate(false)} onConfirm={() => { deactivateDestination(destination.id); setDeactivate(false); setNotice('Destination deactivated. Existing Hotel relationships were preserved.') }} />
  </section>
}
