import { ArrowRight, Clock3, MapPin, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router'
import ManagementSelect from '../../components/ManagementSelect/ManagementSelect.jsx'
import useDestinations from '../../context/useDestinations.js'
import usePropertyContent from '../../context/usePropertyContent.js'
import { categoryLabel, contentTypeLabel, EXPERIENCE_CATEGORIES, getActiveExperiences, getExperienceHeroImage, getExperiencesByCategory, getExperiencesByDestination, normalizeId } from '../../utils/contentDomain.js'
import './Experiences.css'

export default function Experiences() {
  const { experiences } = usePropertyContent(); const { activeDestinations } = useDestinations(); const [category, setCategory] = useState(''); const [destinationId, setDestinationId] = useState('')
  const filtered = useMemo(() => getExperiencesByDestination(getExperiencesByCategory(getActiveExperiences(experiences), category), destinationId).sort((a,b)=>(a.displayOrder||999)-(b.displayOrder||999)||String(a.title).localeCompare(b.title)), [experiences,category,destinationId]); const destination = activeDestinations.find((item)=>normalizeId(item.id)===normalizeId(destinationId)); const clear=()=>{setCategory('');setDestinationId('')}
  return <main className="experience-discovery"><header className="experience-discovery-hero"><span>Curated journeys and stories</span><h1>Experiences in Sri Lanka</h1><p>Discover Sri Lankan culture, nature, coast, food and adventure through carefully selected Experiences and editorial Stories.</p></header><section className="experience-filter-bar" aria-label="Filter Experiences"><div className="experience-category-chips"><button type="button" aria-pressed={!category} onClick={()=>setCategory('')}>All</button>{EXPERIENCE_CATEGORIES.map(([key,label])=><button type="button" aria-pressed={category===key} key={key} onClick={()=>setCategory(key)}>{label}</button>)}</div><div><ManagementSelect label="Destination" value={destinationId} options={[{value:'',label:'All Destinations'},...activeDestinations.map((item)=>({value:String(item.id),label:item.name}))]} onChange={setDestinationId}/>{(category||destinationId)&&<button className="clear-experience-filters" type="button" onClick={clear}><X size={14}/>Clear Filters</button>}</div></section>{filtered.length?<section className="experience-editorial-list" aria-live="polite">{filtered.map((item,index)=>{const place=activeDestinations.find((entry)=>normalizeId(entry.id)===normalizeId(item.destinationId));return <article className={index%2?'reverse':''} key={item.id}><Link className="experience-editorial-image" to={`/experiences/${item.slug}`}><img loading={index?'lazy':'eager'} src={getExperienceHeroImage(item)} alt={item.title}/></Link><div><span>{contentTypeLabel(item.contentType)} · {categoryLabel(item.category)}</span><h2>{item.title}</h2><p>{item.shortDescription}</p><ul>{(place||item.locationText)&&<li><MapPin size={15}/>{place?.name||item.locationText}</li>}{item.contentType==='EXPERIENCE'&&item.duration&&<li><Clock3 size={15}/>{item.duration}</li>}</ul><Link to={`/experiences/${item.slug}`}>{item.contentType==='TRAVEL_STORY'?'Read Story':'Discover Experience'}<ArrowRight size={16}/></Link></div></article>})}</section>:<section className="experience-filter-empty"><h2>No {category?categoryLabel(category):''} Experiences are currently available{destination?` in ${destination.name}`:''}.</h2><button type="button" onClick={clear}>Clear Filters</button></section>}</main>
}
