import { Check, ChevronDown, Search } from 'lucide-react'
import { useEffect, useId, useMemo, useRef, useState } from 'react'
import './ManagementSelect.css'

export default function ManagementSelect({ label, value, options, onChange, required = false, helper, error, searchable = false, placeholder = 'Select' }) {
  const id = useId(); const root = useRef(null); const trigger = useRef(null); const searchInput = useRef(null); const [open, setOpen] = useState(false); const [query, setQuery] = useState('')
  const filtered = useMemo(() => options.filter((item) => !query || `${item.label} ${item.description || ''}`.toLowerCase().includes(query.toLowerCase())), [options, query])
  const selected = options.find((item) => String(item.value) === String(value)); const selectedIndex = Math.max(0, filtered.findIndex((item) => String(item.value) === String(value))); const [activeIndex, setActiveIndex] = useState(selectedIndex)
  useEffect(() => { const close = (event) => { if (!root.current?.contains(event.target)) { setOpen(false); setQuery('') } }; document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close) }, [])
  useEffect(() => setActiveIndex(selectedIndex), [selectedIndex])
  useEffect(() => { if (open && searchable) window.requestAnimationFrame(() => searchInput.current?.focus()) }, [open, searchable])
  const choose = (index) => { const item = filtered[index]; if (!item) return; onChange(item.value); setOpen(false); setQuery(''); trigger.current?.focus() }
  const keyDown = (event) => { if (event.key === 'Tab') { setOpen(false); setQuery(''); return } if (event.key === 'Escape') { event.preventDefault(); setOpen(false); setQuery(''); trigger.current?.focus(); return } if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); setOpen(true); setActiveIndex((index) => filtered.length ? (index + (event.key === 'ArrowDown' ? 1 : -1) + filtered.length) % filtered.length : 0); return } if ((event.key === 'Enter' || event.key === ' ') && !open) { event.preventDefault(); setOpen(true); return } if (event.key === 'Enter' && open) { event.preventDefault(); choose(activeIndex) } }
  return <div className="management-select" ref={root}><label id={`${id}-label`}>{label}{required && ' *'}</label><button ref={trigger} type="button" aria-labelledby={`${id}-label ${id}-value`} aria-haspopup="listbox" aria-expanded={open} aria-controls={`${id}-menu`} className={error ? 'has-error' : ''} onClick={() => setOpen((state) => !state)} onKeyDown={keyDown}><span id={`${id}-value`}>{selected?.label || placeholder}</span><ChevronDown size={16} /></button>{open && <div id={`${id}-menu`} className="management-select-menu" role="listbox" aria-labelledby={`${id}-label`} onKeyDown={keyDown}>{searchable && <label className="management-select-search"><Search size={15} /><span className="sr-only">Search {label}</span><input ref={searchInput} value={query} onChange={(event) => { setQuery(event.target.value); setActiveIndex(0) }} placeholder={`Search ${label.toLowerCase()}`} /></label>}<div>{filtered.map((item, index) => <button type="button" role="option" aria-selected={String(item.value) === String(value)} className={index === activeIndex ? 'is-active' : ''} key={String(item.value)} onMouseEnter={() => setActiveIndex(index)} onClick={() => choose(index)}><span>{String(item.value) === String(value) && <Check size={14} />}<strong>{item.label}</strong>{item.description && <small>{item.description}</small>}</span></button>)}{!filtered.length && <p className="management-select-empty">No matching options</p>}</div></div>}{helper && <small className="management-select-help">{helper}</small>}{error && <small className="rates-field-error" role="alert">{error}</small>}</div>
}
