package com.lankastay.backend.entity;

public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    PASSWORD_CHANGED,
    INITIAL_PASSWORD_CHANGED,
    STAFF_CREATED,
    PASSWORD_RESET_BY_ADMIN,
    ACCOUNT_DISABLED,
    ACCOUNT_ENABLED,
    ROLE_CHANGED,
    LOGOUT,
    HOTEL_CREATED,
    HOTEL_UPDATED,
    HOTEL_ACTIVATED,
    HOTEL_DEACTIVATED,
    HOTEL_DELETED,
    CUSTOMER_REGISTERED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_RESET_FAILED
    ,RESERVATION_CREATED, RESERVATION_CANCELLED, RESERVATION_COMPLETED,
    RESERVATION_DELETED, RESERVATION_ROOM_ASSIGNED
}
