import { Accessibility, Baby, CalendarClock, CalendarX, CigaretteOff, Eye, PawPrint, Pencil, Plus, ShieldCheck, UsersRound } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router'
import ManagementDialog from '../../components/ManagementDialog/ManagementDialog.jsx'
import ManagementSelect from '../../components/ManagementSelect/ManagementSelect.jsx'
import useHotels from '../../context/useHotels.js'
import './HotelPoliciesManager.css'

const categories = [
  ['CHECK_IN_OUT', 'Check-in & Check-out', CalendarClock], ['CANCELLATION', 'Cancellation', CalendarX], ['CHILDREN_BEDS', 'Children & Extra Beds', Baby],
  ['PETS', 'Pets', PawPrint], ['SMOKING', 'Smoking', CigaretteOff], ['ACCESSIBILITY', 'Accessibility', Accessibility], ['HOUSE_RULES', 'House Rules', UsersRound], ['OTHER', 'Other / Custom', ShieldCheck],
]
const blank = { title: '', category: 'CHECK_IN_OUT', summary: '', details: '', status: 'ACTIVE' }
const categoryMeta = (value) => categories.find(([key]) => key === value) || categories.at(-1)
const normalizeCategory = (value) => ({ 'Check-in': 'CHECK_IN_OUT', 'Check-out': 'CHECK_IN_OUT', Cancellation: 'CANCELLATION', Children: 'CHILDREN_BEDS', Pets: 'PETS', Smoking: 'SMOKING', Accessibility: 'ACCESSIBILITY', 'House Rules': 'HOUSE_RULES', General: 'OTHER' })[value] || (categories.some(([key]) => key === value) ? value : 'OTHER')

export default function HotelPoliciesManager({ hotel, readiness, onPublish }) {
  const { updateHotel, updateSetupSection } = useHotels()
  const initial = (hotel.policyRecords || Object.entries(hotel.managementPolicies || {}).filter(([, value]) => value).map(([category, details], index) => ({ id: `legacy-${index}`, title: `${category.charAt(0).toUpperCase()}${category.slice(1)} Policy`, category: 'OTHER', summary: String(details), details: String(details), status: 'ACTIVE' }))).map((policy) => ({ ...policy, category: normalizeCategory(policy.category) }))
  const [records, setRecords] = useState(initial); const [editing, setEditing] = useState(null); const [viewing, setViewing] = useState(null); const [statusTarget, setStatusTarget] = useState(null)
  const [form, setForm] = useState(blank); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const activeCount = records.filter((item) => item.status === 'ACTIVE').length
  const commit = (next, text) => { setRecords(next); updateHotel(hotel.id, { policyRecords: next, lastUpdatedSection: 'Policies' }); updateSetupSection(hotel.id, 'policies', next.some((item) => item.status === 'ACTIVE'), { policyRecords: next }); setMessage(text) }
  const startAdd = () => { setEditing(null); setForm(blank); setError(''); document.querySelector('#policy-editor')?.scrollIntoView({ behavior: 'smooth' }) }
  const startEdit = (policy) => { setEditing(policy.id); setForm({ title: policy.title, category: policy.category || 'OTHER', summary: policy.summary, details: Array.isArray(policy.details) ? policy.details.join('\n') : policy.details, status: policy.status }); setError(''); document.querySelector('#policy-editor')?.scrollIntoView({ behavior: 'smooth' }) }
  const submit = (event) => {
    event.preventDefault(); if (!form.title.trim() || !form.category || !form.summary.trim() || !form.details.trim()) return setError('Policy title, category, summary and full details are required.')
    const payload = { ...form, title: form.title.trim(), summary: form.summary.trim(), details: form.details.trim() }
    const next = editing ? records.map((item) => item.id === editing ? { ...item, ...payload } : item) : [...records, { ...payload, id: `policy-${Date.now()}` }]
    commit(next, `Policy ${editing ? 'updated' : 'added'} for ${hotel.name}.`); setEditing(null); setForm(blank); setError('')
  }
  const toggleStatus = () => { const nextStatus = statusTarget.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'; commit(records.map((item) => item.id === statusTarget.id ? { ...item, status: nextStatus } : item), `Policy ${nextStatus === 'ACTIVE' ? 'activated for customer display' : 'deactivated and retained in Management'}.`); setStatusTarget(null) }

  return <section className="policy-workspace">
    <header className="policy-workspace-header"><div><span>Required property content</span><h2>Hotel Policies · {hotel.name}</h2><p>Create clear stay information shared by Preview and the customer Hotel page.</p></div><button type="button" onClick={startAdd}><Plus size={16} />Add Policy</button></header>
    <div className="policy-summary"><article><small>Total Policies</small><strong>{records.length}</strong></article><article><small>Active Policies</small><strong>{activeCount}</strong></article><article><small>Inactive Policies</small><strong>{records.length - activeCount}</strong></article><article><small>Readiness</small><strong>{activeCount ? 'Complete' : 'Policy required'}</strong></article></div>
    {message && <p className="property-success" role="status" aria-live="polite">{message}</p>}
    {records.length ? <div className="policy-card-grid">{records.map((policy) => { const [, label, Icon] = categoryMeta(policy.category); return <article className={policy.status !== 'ACTIVE' ? 'inactive' : ''} key={policy.id}><div className="policy-card-heading"><span><Icon size={19} /></span><div><small>{label}</small><h3>{policy.title}</h3></div><strong className={policy.status === 'ACTIVE' ? 'active' : ''}>{policy.status === 'ACTIVE' ? 'Active' : 'Inactive'}</strong></div><p>{policy.summary}</p><div><button type="button" onClick={() => setViewing(policy)}><Eye size={14} />View</button><button type="button" onClick={() => startEdit(policy)}><Pencil size={14} />Edit</button><button type="button" className={policy.status === 'ACTIVE' ? 'danger' : ''} onClick={() => setStatusTarget(policy)}>{policy.status === 'ACTIVE' ? 'Deactivate' : 'Activate'}</button></div></article>})}</div> : <div className="content-empty"><span><ShieldCheck size={25} /></span><h3>No policies have been configured.</h3><p>Add at least one active policy before this Hotel can be published.</p><button type="button" onClick={startAdd}>Add Policy</button></div>}
    <form className="policy-form" id="policy-editor" onSubmit={submit} noValidate><div className="policy-form-heading"><div><span>Policy record</span><h3>{editing ? 'Edit Policy' : 'Add Policy'}</h3></div>{editing && <button type="button" onClick={() => { setEditing(null); setForm(blank); setError('') }}>Cancel Edit</button>}</div><div className="policy-form-grid"><label><span>Policy Title *</span><input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><ManagementSelect label="Category" required value={form.category} options={categories.map(([value, label]) => ({ value, label }))} onChange={(value) => setForm({ ...form, category: value })} /><label className="wide"><span>Summary *</span><textarea rows="3" value={form.summary} onChange={(event) => setForm({ ...form, summary: event.target.value })} /></label><label className="wide"><span>Full Details *</span><textarea rows="6" value={form.details} onChange={(event) => setForm({ ...form, details: event.target.value })} /><small>Use separate lines when the policy has multiple points.</small></label><ManagementSelect label="Status" value={form.status} options={[{ value: 'ACTIVE', label: 'Active' }, { value: 'INACTIVE', label: 'Inactive' }]} onChange={(value) => setForm({ ...form, status: value })} />{error && <p className="property-error wide" role="alert">{error}</p>}</div><div className="policy-form-actions"><button className="primary" type="submit">{editing ? 'Save Policy Changes' : 'Add Policy'}</button></div></form>
    <div className="policy-final-actions"><div><strong>{readiness.canPublish ? 'Required setup complete' : 'Complete setup to publish'}</strong>{!readiness.canPublish && <small>Missing: {readiness.incompleteRequired.map((item) => item.label).join(', ')}</small>}</div><button type="button" onClick={() => setMessage('Policies are already synchronized with the shared Hotel state.')}>Save Policies</button><Link to={`/management/hotels/${hotel.id}/preview`}>Preview Hotel</Link><button className="primary" type="button" disabled={!readiness.canPublish} onClick={onPublish}>{readiness.canPublish ? 'Publish Hotel' : 'Complete Setup to Publish'}</button></div>
    {viewing && <ManagementDialog title={viewing.title} description={`${categoryMeta(viewing.category)[1]} · ${viewing.status === 'ACTIVE' ? 'Active' : 'Inactive'}`} onClose={() => setViewing(null)} actions={<><button type="button" onClick={() => setViewing(null)}>Close</button><button className="primary" type="button" onClick={() => { startEdit(viewing); setViewing(null) }}>Edit Policy</button></>}><div className="policy-view"><strong>{viewing.summary}</strong><p>{viewing.details}</p></div></ManagementDialog>}
    {statusTarget && <ManagementDialog danger={statusTarget.status === 'ACTIVE'} title={`${statusTarget.status === 'ACTIVE' ? 'Deactivate' : 'Activate'} ${statusTarget.title}?`} description={statusTarget.status === 'ACTIVE' ? 'This policy will remain in Management but will no longer appear to customers.' : 'This policy will become visible on the customer Hotel page and manager Preview.'} onClose={() => setStatusTarget(null)} actions={<><button type="button" onClick={() => setStatusTarget(null)}>Cancel</button><button className={statusTarget.status === 'ACTIVE' ? 'danger' : 'primary'} type="button" onClick={toggleStatus}>{statusTarget.status === 'ACTIVE' ? 'Deactivate Policy' : 'Activate Policy'}</button></>} />}
  </section>
}
