import { Check, Eye, Pencil, Plus, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import ManagementDialog from '../../components/ManagementDialog/ManagementDialog.jsx'
import usePropertyContent from '../../context/usePropertyContent.js'
import { facilityIconOptions, getFacilityIcon } from '../../utils/facilityIcons.js'
import './PropertyEditors.css'
import './HotelFacilitiesManager.css'

const blank = { name: '', iconKey: 'wifi', category: '', active: true }

export default function HotelFacilitiesManager({ hotel, updateSetupSection, onContinue }) {
  const { facilities, addFacility, updateFacility, activateFacility, deactivateFacility } = usePropertyContent()
  const initialSelected = useMemo(() => hotel.facilityIds || facilities.filter((facility) => (hotel.facilities || []).some((name) => name.toLowerCase() === facility.name.toLowerCase())).map((facility) => facility.id), [hotel.facilityIds, hotel.facilities, facilities])
  const [selected, setSelected] = useState(initialSelected); const [editing, setEditing] = useState(null); const [viewing, setViewing] = useState(null); const [statusTarget, setStatusTarget] = useState(null)
  const [form, setForm] = useState(blank); const [search, setSearch] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const visible = facilities.filter((facility) => `${facility.name} ${facility.category || 'General'}`.toLowerCase().includes(search.trim().toLowerCase()))
  const groups = Object.entries(visible.reduce((result, facility) => { const category = facility.category || 'General'; (result[category] ||= []).push(facility); return result }, {})).sort(([a], [b]) => a.localeCompare(b))
  const saveSelection = (next, text = 'Hotel facilities saved.') => { setSelected(next); updateSetupSection(hotel.id, 'facilities', next.length > 0, { facilityIds: next }); setMessage(text) }
  const toggle = (facility) => { if (!facility.active && !selected.includes(facility.id)) return; saveSelection(selected.includes(facility.id) ? selected.filter((id) => id !== facility.id) : [...selected, facility.id]) }
  const edit = (facility) => { setEditing(facility.id); setForm({ name: facility.name, iconKey: facility.iconKey, category: facility.category || '', active: facility.active }); setError('') }
  const submit = (event) => { event.preventDefault(); const name = form.name.trim(); if (!name) return setError('Facility Name is required.'); if (facilities.some((facility) => String(facility.id) !== String(editing || '') && facility.name.toLowerCase() === name.toLowerCase())) return setError('A facility with this name already exists.'); if (editing) { updateFacility(editing, { ...form, name }); setMessage('Facility updated.') } else { const created = addFacility({ ...form, name }); saveSelection([...selected, created.id], 'Facility created and selected for this Hotel.') } setEditing(null); setForm(blank); setError('') }
  const toggleDefinition = () => { if (statusTarget.active) deactivateFacility(statusTarget.id); else activateFacility(statusTarget.id); setMessage(`${statusTarget.name} ${statusTarget.active ? 'deactivated; existing Hotel relationships were retained' : 'activated for selection'}.`); setStatusTarget(null) }

  return <article className="hotel-workspace-card property-editor">
    <div className="property-editor-heading"><div><span>Required shared definitions</span><h2>Hotel Facilities</h2><p>{hotel.name} · {selected.length} selected · {facilities.filter((item) => item.active).length} active definitions</p></div></div>
    {message && <p className="property-success" role="status" aria-live="polite">{message}</p>}
    <label className="facility-search"><span><Search size={15} />Search Facilities</span><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or category" /></label>
    {groups.length ? groups.map(([category, items]) => <section className="facility-group" key={category}><h3>{category}</h3><div className="facility-grid">{items.map((facility) => { const Icon = getFacilityIcon(facility.iconKey); const checked = selected.includes(facility.id); return <div className={`facility-check-card${checked ? ' selected' : ''}${!facility.active ? ' inactive' : ''}`} key={facility.id}><label><input type="checkbox" checked={checked} disabled={!facility.active && !checked} onChange={() => toggle(facility)} /><span className="facility-check-icon"><Icon size={19} /></span><strong>{facility.name}</strong><small>{facility.active ? 'Active' : 'Inactive'}</small>{checked && <Check className="facility-check-mark" size={15} />}</label><div className="facility-card-actions"><button type="button" aria-label={`View ${facility.name}`} onClick={() => setViewing(facility)}><Eye size={13} /></button><button type="button" aria-label={`Edit ${facility.name}`} onClick={() => edit(facility)}><Pencil size={13} /></button></div></div>})}</div></section>) : <p className="property-error">No Facilities match this search.</p>}
    <form className="property-inline-form" onSubmit={submit}><div className="property-inline-title"><Plus size={16} /><h3>{editing ? 'Edit Facility' : 'Add Facility'}</h3></div><label><span>Facility Name *</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label><span>Category</span><input value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} /></label><fieldset className="icon-picker"><legend>Icon *</legend>{facilityIconOptions.map(([key, label]) => { const Icon = getFacilityIcon(key); return <label className={form.iconKey === key ? 'selected' : ''} key={key}><input type="radio" name="facility-icon" checked={form.iconKey === key} onChange={() => setForm({ ...form, iconKey: key })} /><Icon size={17} /><span>{label}</span></label> })}</fieldset>{error && <p className="property-error" role="alert">{error}</p>}<div className="property-form-actions"><button type="submit">{editing ? 'Save Facility' : 'Add Facility'}</button>{editing && <><button type="button" className="secondary" onClick={() => { setEditing(null); setForm(blank); setError('') }}>Cancel</button><button type="button" className="secondary" onClick={() => setStatusTarget(facilities.find((item) => item.id === editing))}>{facilities.find((item) => item.id === editing)?.active ? 'Deactivate' : 'Activate'}</button></>}</div></form>
    <div className="facility-final-actions"><button type="button" onClick={() => saveSelection(selected)}>Save Facilities</button><button className="primary" type="button" onClick={() => { saveSelection(selected); onContinue?.('gallery') }}>Save &amp; Continue to Gallery</button></div>
    {viewing && <ManagementDialog title={viewing.name} description={`${viewing.category || 'General'} · ${viewing.active ? 'Active' : 'Inactive'}`} onClose={() => setViewing(null)} actions={<><button type="button" onClick={() => setViewing(null)}>Close</button><button className="primary" type="button" onClick={() => { edit(viewing); setViewing(null) }}>Edit Facility</button></>}><p>This shared definition is {selected.includes(viewing.id) ? `selected for ${hotel.name}` : `not selected for ${hotel.name}`}.</p></ManagementDialog>}
    {statusTarget && <ManagementDialog danger={statusTarget.active} title={`${statusTarget.active ? 'Deactivate' : 'Activate'} ${statusTarget.name}?`} description={statusTarget.active ? 'It will be unavailable for new Hotel assignments. Existing relationships remain retained.' : 'It will become available for Hotel assignment again.'} onClose={() => setStatusTarget(null)} actions={<><button type="button" onClick={() => setStatusTarget(null)}>Cancel</button><button className={statusTarget.active ? 'danger' : 'primary'} type="button" onClick={toggleDefinition}>{statusTarget.active ? 'Deactivate' : 'Activate'}</button></>} />}
  </article>
}
